# Code Generated by Sidekick is for learning and experimentation purposes only.
[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$ProjectId,

  [string]$Region = "us-central1",
  [string]$Zone   = "us-central1-a",

  [string]$ClusterName = "demo-gke",
  [string]$NetworkName = "demo-vpc",
  [string]$SubnetName  = "demo-subnet",

  [string]$SubnetCidr   = "10.10.0.0/20",
  [string]$PodRangeName = "gke-pods",
  [string]$PodCidr      = "10.20.0.0/16",
  [string]$SvcRangeName = "gke-services",
  [string]$SvcCidr      = "10.30.0.0/20",

  [string]$NodeSaName = "gke-node-sa",

  # Native GKE supports SYSTEM or NONE (NOT SYSTEM,WORKLOAD)
  [ValidateSet("SYSTEM","NONE")]
  [string]$Logging = "SYSTEM",

  [ValidateSet("SYSTEM","NONE")]
  [string]$Monitoring = "SYSTEM",

  # Optional: if your org requires an environment tag, pass the Tag Value resource name:
  # Example format: "tagValues/123456789012"
  [string]$EnvironmentTagValueResource = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# PS7 fix: prevent native-app stderr (e.g., gcloud 404) from becoming terminating errors
if (Get-Variable -Name PSNativeCommandUseErrorActionPreference -Scope Global -ErrorAction SilentlyContinue) {
  $global:PSNativeCommandUseErrorActionPreference = $false
}

$NodeSa = "$NodeSaName@$ProjectId.iam.gserviceaccount.com"

function Invoke-Gcloud {
  param([Parameter(Mandatory=$true)][string[]]$Args)
  & gcloud @Args
  if ($LASTEXITCODE -ne 0) { throw "gcloud failed: gcloud $($Args -join ' ')" }
}

function Test-GcloudOk {
  param([Parameter(Mandatory=$true)][string[]]$Args)

  $oldEap = $ErrorActionPreference
  try {
    # Ensure "not found" checks don't terminate the script in PS7
    $ErrorActionPreference = "Continue"
    & gcloud @Args *> $null 2>$null
    return ($LASTEXITCODE -eq 0)
  }
  finally {
    $ErrorActionPreference = $oldEap
  }
}

function Invoke-Kubectl {
  param([Parameter(Mandatory=$true)][string[]]$Args)
  & kubectl @Args
  if ($LASTEXITCODE -ne 0) { throw "kubectl failed: kubectl $($Args -join ' ')" }
}

try {
  Write-Host "== Set project/region ==" -ForegroundColor Cyan
  Invoke-Gcloud @("config","set","project",$ProjectId)
  Invoke-Gcloud @("config","set","compute/region",$Region)
  Invoke-Gcloud @("config","set","compute/zone",$Zone)

  Write-Host "== Enable required APIs ==" -ForegroundColor Cyan
  Invoke-Gcloud @("services","enable",
    "compute.googleapis.com",
    "container.googleapis.com",
    "iam.googleapis.com",
    "cloudresourcemanager.googleapis.com",
    "artifactregistry.googleapis.com",
    "cloudbuild.googleapis.com",
    "logging.googleapis.com",
    "monitoring.googleapis.com"
  )

  if ($EnvironmentTagValueResource) {
    Write-Host "== Optional: bind environment tag to project ==" -ForegroundColor Cyan
    $projectNumber = (& gcloud projects describe $ProjectId --format="value(projectNumber)" 2>$null).Trim()
    if (-not $projectNumber) { throw "Could not resolve projectNumber for $ProjectId" }

    $parent = "//cloudresourcemanager.googleapis.com/projects/$projectNumber"
    $already = & gcloud resource-manager tags bindings list --parent=$parent --format="value(tagValue)" 2>$null

    if ($already -and ($already -contains $EnvironmentTagValueResource)) {
      Write-Host "Tag already bound, skipping: $EnvironmentTagValueResource" -ForegroundColor DarkGray
    } else {
      Invoke-Gcloud @("resource-manager","tags","bindings","create","--tag-value",$EnvironmentTagValueResource,"--parent",$parent)
    }
  }

  Write-Host "== Create VPC + Subnet (idempotent) ==" -ForegroundColor Cyan
  if (-not (Test-GcloudOk @("compute","networks","describe",$NetworkName,"--format=value(name)"))) {
    Invoke-Gcloud @("compute","networks","create",$NetworkName,"--subnet-mode=custom")
  } else {
    Write-Host "VPC exists, skipping: $NetworkName" -ForegroundColor DarkGray
  }

  if (-not (Test-GcloudOk @("compute","networks","subnets","describe",$SubnetName,"--region",$Region,"--format=value(name)"))) {
    Invoke-Gcloud @(
      "compute","networks","subnets","create",$SubnetName,
      "--network",$NetworkName,
      "--region",$Region,
      "--range",$SubnetCidr,
      "--secondary-range",("$PodRangeName=$PodCidr,$SvcRangeName=$SvcCidr")
    )
  } else {
    Write-Host "Subnet exists, skipping: $SubnetName" -ForegroundColor DarkGray
  }

  Write-Host "== Create node service account (idempotent) ==" -ForegroundColor Cyan
  if (-not (Test-GcloudOk @("iam","service-accounts","describe",$NodeSa,"--format=value(email)"))) {
    Invoke-Gcloud @("iam","service-accounts","create",$NodeSaName,"--display-name","GKE Node SA ($ClusterName)")
  } else {
    Write-Host "Service account exists, skipping: $NodeSa" -ForegroundColor DarkGray
  }

  Write-Host "== Bind baseline IAM roles to node SA ==" -ForegroundColor Cyan
  Invoke-Gcloud @("projects","add-iam-policy-binding",$ProjectId,"--member","serviceAccount:$NodeSa","--role","roles/logging.logWriter","--quiet")
  Invoke-Gcloud @("projects","add-iam-policy-binding",$ProjectId,"--member","serviceAccount:$NodeSa","--role","roles/monitoring.metricWriter","--quiet")
  Invoke-Gcloud @("projects","add-iam-policy-binding",$ProjectId,"--member","serviceAccount:$NodeSa","--role","roles/monitoring.viewer","--quiet")
  Invoke-Gcloud @("projects","add-iam-policy-binding",$ProjectId,"--member","serviceAccount:$NodeSa","--role","roles/stackdriver.resourceMetadata.writer","--quiet")

  Write-Host "== Create regional GKE cluster (idempotent) ==" -ForegroundColor Cyan
  $clusterExists = Test-GcloudOk @("container","clusters","describe",$ClusterName,"--region",$Region,"--format=value(name)")
  if (-not $clusterExists) {
    Invoke-Gcloud @(
      "container","clusters","create",$ClusterName,
      "--region",$Region,
      "--release-channel","regular",
      "--network",$NetworkName,
      "--subnetwork",$SubnetName,
      "--cluster-secondary-range-name",$PodRangeName,
      "--services-secondary-range-name",$SvcRangeName,
      "--workload-pool","$ProjectId.svc.id.goog",
      "--enable-ip-alias",
      "--enable-shielded-nodes",
      "--enable-autoupgrade",
      "--enable-autorepair",
      "--logging=$Logging",
      "--monitoring=$Monitoring",
      "--num-nodes","2",
      "--machine-type","e2-standard-4",
      "--service-account",$NodeSa,
      "--enable-autoscaling","--min-nodes","2","--max-nodes","5"
    )
  } else {
    Write-Host "Cluster exists, skipping create: $ClusterName" -ForegroundColor DarkGray
  }

  Write-Host "== Get kubeconfig credentials ==" -ForegroundColor Cyan
  Invoke-Gcloud @("container","clusters","get-credentials",$ClusterName,"--region",$Region)

  Write-Host "== Create namespace and deploy sample app ==" -ForegroundColor Cyan
  & kubectl create namespace demo 2>$null | Out-Null

  $manifest = @'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-lb
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - name: http
    port: 80
    targetPort: 8080
'@

  $manifest | & kubectl -n demo apply -f - | Out-Host
  Invoke-Kubectl @("-n","demo","rollout","status","deploy/hello")

  Write-Host "== Wait for external IP ==" -ForegroundColor Cyan
  $externalIp = ""
  for ($i=0; $i -lt 60; $i++) {
    $externalIp = (& kubectl -n demo get svc hello-lb -o jsonpath="{.status.loadBalancer.ingress[0].ip}" 2>$null)
    if ($externalIp) { break }
    Start-Sleep -Seconds 5
  }

  Write-Host "Service External IP: $externalIp" -ForegroundColor Green
  if ($externalIp) { Write-Host "Test: curl http://$externalIp/" -ForegroundColor Yellow }

  Write-Host "== Add HPA ==" -ForegroundColor Cyan
  Invoke-Kubectl @("-n","demo","autoscale","deployment","hello","--cpu-percent=50","--min=2","--max=6")

  Write-Host "== Show status ==" -ForegroundColor Cyan
  Invoke-Kubectl @("-n","demo","get","all")
  Invoke-Kubectl @("-n","demo","get","hpa")

  Write-Host "Optional load test (separate terminal):" -ForegroundColor Yellow
  Write-Host "kubectl -n demo run -it --rm loadgen --image=busybox:1.36 --restart=Never -- sh -c 'while true; do wget -q -O- http://hello-lb.demo.svc.cluster.local >/dev/null; done'"
}
catch {
  Write-Host "`nFAILED: $($_.Exception.Message)`n" -ForegroundColor Red
  throw
}
