# Code Generated by Sidekick is for learning and experimentation purposes only.
[CmdletBinding()]
param(
  [Parameter(Mandatory=$true)][string]$ProjectId,

  [string]$Region = "us-central1",
  [string]$ClusterName = "demo-gke",
  [string]$NetworkName = "demo-vpc",
  [string]$SubnetName  = "demo-subnet",
  [string]$NodeSaName  = "gke-node-sa"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$NodeSa = "$NodeSaName@$ProjectId.iam.gserviceaccount.com"

function Invoke-GcloudSoft {
  param([Parameter(Mandatory=$true)][string[]]$Args)
  & gcloud @Args
  if ($LASTEXITCODE -ne 0) { Write-Host "Warn: gcloud failed (continuing): gcloud $($Args -join ' ')" -ForegroundColor DarkYellow }
}
function Test-GcloudOk {
  param([Parameter(Mandatory=$true)][string[]]$Args)
  & gcloud @Args *> $null
  return ($LASTEXITCODE -eq 0)
}

Invoke-GcloudSoft @("config","set","project",$ProjectId)

Write-Host "== Delete cluster (if exists) ==" -ForegroundColor Cyan
if (Test-GcloudOk @("container","clusters","describe",$ClusterName,"--region",$Region,"--format=value(name)")) {
  Invoke-GcloudSoft @("container","clusters","delete",$ClusterName,"--region",$Region,"--quiet")
} else {
  Write-Host "Cluster not found, skipping: $ClusterName" -ForegroundColor DarkGray
}

Write-Host "== Delete subnet + VPC (if exist) ==" -ForegroundColor Cyan
if (Test-GcloudOk @("compute","networks","subnets","describe",$SubnetName,"--region",$Region,"--format=value(name)")) {
  Invoke-GcloudSoft @("compute","networks","subnets","delete",$SubnetName,"--region",$Region,"--quiet")
} else {
  Write-Host "Subnet not found, skipping: $SubnetName" -ForegroundColor DarkGray
}

if (Test-GcloudOk @("compute","networks","describe",$NetworkName,"--format=value(name)")) {
  Invoke-GcloudSoft @("compute","networks","delete",$NetworkName,"--quiet")
} else {
  Write-Host "VPC not found, skipping: $NetworkName" -ForegroundColor DarkGray
}

Write-Host "== Delete node service account (if exists) ==" -ForegroundColor Cyan
if (Test-GcloudOk @("iam","service-accounts","describe",$NodeSa,"--format=value(email)")) {
  Invoke-GcloudSoft @("iam","service-accounts","delete",$NodeSa,"--quiet")
} else {
  Write-Host "Service account not found, skipping: $NodeSa" -ForegroundColor DarkGray
}

Write-Host "Cleanup complete." -ForegroundColor Green
